export const en ={
    Email: 'Email',
    Password: 'Password',
    Login: 'LOGIN',
    WrongInfo: '"Wrong account or password"',
    Logging: 'Logging In',
    WrongFA: 'Please enter username and password',
    EnableFA: 'Please enable {{faMethod}} in app first!',
    SetUpFA: 'In order to use {{faMethod}}. Please set up your {{faMethod}} first!',
    InvalidEmail:'Email is Invalid',
    EmptyEmail:'Please enter username',
    EmptyPassword:'Please enter password',
    minLength:'Password must be at least {{pwLength}} characters',
    RT:'Real Time Conditions',
    Account:'Account',
    Logout:'Log out',
    Details:'Tracker Details',
    MapRoute:"Map Route",
    Linkage:'Linkage',
    WL:'White List',
    WLNav:'White List',
    OK:'OK',
    Code:'Plant Code',
    Name:'Plant Name ',
    Location:'Location Remarks',
    LINK:'LINK',
    selected:'Selected',
    NoImage:'No Images Found',
    back:'back',
    finish:'finish',
    Project:'Project No.',
    AddWatch:'Add Smartwatch User',
    Confirm:'CONFIRM',
    LogOut:'LOGOUT',
    Forget:'Forget your password?',
    Connect:'CONNECT',
    Setting:'Account Setting',
    Disable:'Disable',
    Enable:'Enable',
    SelectLang:'Please select language',
    Cancel:'Cancel',
    Change:'Change',
    SureLogout:'Are you sure you want to logout?',
    FunctionalDes:'If other smartwatch users close to the plant, you will be alerted',
    Scan:'Scanning Nearby',
    User:' Smartwatch Users',
    Neatby:'Neatby',
    Series:'Series',
    Paired:'Paired',    
    Plant:' Plant',
    LastUpated:'Last Updated at',
    Connecting:'Connecting',
    Upload:'Upload',
    Image:' Image(s)',
    LastUpdatedAt:'Last updated at {{time}}',
    Pair:'Pair',
    Unlink:'Unlink',
    ss:'(s)',
    ForgetUsername:'Please enter your email',
    Send:'SEND',
    UploadFromAlbum:'Upload From Album',
    Camera:'Camera',
    SmartWatch:'smartwatch',
    Your:' your ',
    Nearby:' Nearby' ,
    Searching:'Searching',
    atLessOne:'At least one user is added.',
    atLessOneP:'Please select',
    ConnectUser:'Please connect to smartwatch(s) first.',
    LogOutAll:'LOGOUT ALL',
    CheckInternet:'Please check the internet connection.',
    UAD:'Unauthorized Device',
    Add:'Add',
    Driver:'Driver',
    Unassigned:'Unassigned Driver',
    Contractor:'Contractor',    
    verify:'Login to verify your identity',
    Version:'Version',
    DataMiss:'Please complete all data.',
    ChangePrj:'Change Project',
    NewV:'New Version',
    UPGRADE:'UPGRADE',
    SelectPrj:'Please select project',
    Accept:'Accept'
}



export const zh ={
    Email: '電郵',
    Password: '密碼',
    Login: '登入',
    WrongInfo: '用戶名或密碼錯誤',
    Logging: '登入中',
    WrongFA: '請輸入用戶名及密碼',
    EnableFA: '請於登入後開啟{{faMethod}}',
    SetUpFA: '若要使用{{faMethod}}，請首先設定手機的{{faMethod}}',
    InvalidEmail:'錯誤電郵格式',
    EmptyEmail:'請輸入用戶名',
    EmptyPassword:'請輸入密碼',
    minLength:'請輸入最少8位數字密碼',
    RT:'實時情況',
    Account:'帳號',
    Logout:'登出',
    Details:'追踪器細節',
    MapRoute:"地圖",
    Linkage:'聯繫',
    WL:'白名單',
    WLNav:'白名單',
    OK:'確定',
    Code:'設備代碼',
    Name:'設備名稱',
    Location:'位置備註',
    LINK:'連接',        
    back:'返回',
    finish:'完成',
    NoImage:'沒有相片',
    selected:'已選擇',
    Project:'項目號碼',
    AddWatch:'新增智能手錶使用者',
    Add:'增加',
    Confirm:'確定',
    LogOut:'登出',
    Forget:'忘記密碼?',
    Connect:'連結',
    Setting:'帳號設定',
    Disable:'禁用',
    Enable:'開啟',
    SelectLang:'請選擇語言',
    Cancel:'取消',
    Change:'更改',
    SureLogout:'確定登出?',
    FunctionalDes:'你將受到警告當有其他智能手錶使用者接近',
    Scan:'掃描附近',
    User:'智能手錶使用者',
    Neatby:'附近有',
    Series:'型號',
    Paired:'已配對',
    Plant:'裝置',
    LastUpated:'最後更新',
    Connecting:'連接中',
    Upload:'上傳',
    Image:'照片',
    LastUpdatedAt:'由{{name}}最後更新在{{time}}',
    Pair:'配對',
    Unlink:'取消連接',
    ss:'',
    ForgetUsername:'請輸入你的電郵',
    Send:'寄出',
    UploadFromAlbum:'於相簿上傳相片',
    Camera:'相機',
    SmartWatch:'智能手錶',
    Your:'你的',
    Nearby:'附近',
    Searching:'尋找',
    atLessOne:'最少新增一名使用者',
    atLessOneP:'請選擇車輛或機械',
    ConnectUser:'請先連接至智能手錶',
    LogOutAll:'登出所有使用者',
    CheckInternet:'請連接上網',
    UAD:'不明裝置',
    Driver:'司機',
    Unassigned:'未指派司機',
    Contractor:'承包商',   
    verify:'請先登入驗證',   
    Version:'版本',
    DataMiss:'請完成所有項目',
    ChangePrj:'更換項目',
    NewV:'新版本',
    UPGRADE:'升級',
    SelectPrj:'請選擇項目',
    Accept:'准許'
}